name: 'Merge master branch to deploy'
description: 'Merges the master branch to a deploy branch every hour'
author: 'FlexMR'
branding:
  icon: 'git-merge'
  color: 'green'
inputs:
  push_token:
    description: 'Contains token to perform git push'
    required: false
    default: 'GITHUB_TOKEN'
runs:
  using: 'docker'
  image: 'Dockerfile'
